### ISSUE TITLE
Print warnings to the console

### ISSUE THREAD

**Issue by marklarr** [supermarin/xcpretty#108]
Discussion started here: https://github.com/marklarr/mayday/issues/3

`xcpretty` currently eats any warning output from `xcodebuild` and doesn't spit it back out.

**Comment by archshift** [comment]
What's the status of the work being done on this?

**Comment by supermarin** [comment]
@archshift the warnings part has been merged into `master` and released separately.

Are you not seeing the warnings printed?

**Comment by archshift** [comment]
So shouldn't this be closed?

**Comment by supermarin** [comment]
@archshift it should, I thought it was :)
Thanks

**Comment by chinhodado** [comment]
Apparently the pre-installed version of xcpretty on Travis still doesn't support warnings yet.
