### ISSUE TITLE
Runtime tests output

### ISSUE THREAD

**Issue by danielgomezrico** [supermarin/xcpretty#119]
I want to use it here because I'm using it to test locally.
Is there anyway to see the actual test in runtime in the terminal like:

-> Runing testShowView

And all the println and NSLog output inside the report like: 

-> Runing testShowView
"printed"
"printed 2"

Success!

-> Runing testShowView
"printed"
"printed 2"

Fail!

**Comment by supermarin** [comment]
@danielgomezrico not in this version, we're [working on a blacklist model](#118) to support random loggings.
