### ISSUE TITLE
Travis Folding Support

### ISSUE THREAD

**Issue by swizzlr** [supermarin/xcpretty#120]
It would be so rad if xcpretty could support this, using this technique:

http://enricostano.github.io/articles/dealing-with-travis-ci-console-output/

**Comment by kattrali** [comment]
@swizzlr I was actually just wondering how the folding works. Interesting. I might poke around with a custom formatter for this, unless someone beats me to it.

**Comment by Ashton-W** [comment]
Nice idea. Where should we place the folding markers in **xcpretty*'s output?

**Comment by swizzlr** [comment]
This is probably a reporter level thing. In the simple output, I'd encourage it to be per build command, and per test suite.

**Comment by kattrali** [comment]
@swizzlr Makes sense to me. I've got the skeleton sketched out here: https://github.com/kattrali/xcpretty-travis-formatter

There might be some other niceties to be added for travis which might also be appropriate to add.

**Comment by Ashton-W** [comment]
We could ask for some input from @Travis-CI

**Comment by kattrali** [comment]
Moving over to https://github.com/kattrali/xcpretty-travis-formatter, let's put new suggestions there so there's no need for specific service stuff in the core gem.
