### ISSUE TITLE
"Expected report format to be specified before output path"

### ISSUE THREAD

**Issue by dtrenz** [supermarin/xcpretty#135]
Why does specifying the output path after the report format cause a fatal error? Does the order really matter that much?

**Comment by kattrali** [comment]
Multiple report types can be generated in a single run, and the output path is assigned to the previous report type specified, like:

    xcpretty -r html -o report.html -r junit -o report.xml

If no report type has been specified, the output path cannot be assigned to a report. [Here is the relevant code](https://github.com/supermarin/xcpretty/blob/master/bin/xcpretty#L56-59).
