### ISSUE TITLE
invalid byte sequence in US-ASCII?

### ISSUE THREAD

**Issue by Ashton-W** [supermarin/xcpretty#137]
A CI box spat this error out during the Analyze phase. Unfortunately I wasn't keeping the xcodebuild logs around, and I haven't seen it happen again..

```
27-Mar-2015 18:55:32	/Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/parser.rb:348:in `===': invalid byte sequence in US-ASCII (ArgumentError)
27-Mar-2015 18:55:32	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/parser.rb:348:in `update_test_state'
27-Mar-2015 18:55:32	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/parser.rb:245:in `parse'
27-Mar-2015 18:55:32	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/formatters/formatter.rb:78:in `pretty_format'
27-Mar-2015 18:55:32	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/printer.rb:15:in `pretty_print'
27-Mar-2015 18:55:32	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/bin/xcpretty:80:in `block in <top (required)>'
27-Mar-2015 18:55:32	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/bin/xcpretty:79:in `each_line'
27-Mar-2015 18:55:32	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/bin/xcpretty:79:in `<top (required)>'
27-Mar-2015 18:55:32	        from /usr/bin/xcpretty:23:in `load'
27-Mar-2015 18:55:32	        from /usr/bin/xcpretty:23:in `<main>'
```

---

Sorry this report is bad, but this is all I have until it happens again.

**Comment by Ashton-W** [comment]
```
10-Apr-2015 09:32:57	/Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/parser.rb:348:in `===': invalid byte sequence in US-ASCII (ArgumentError)
10-Apr-2015 09:32:57	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/parser.rb:348:in `update_test_state'
10-Apr-2015 09:32:57	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/parser.rb:245:in `parse'
10-Apr-2015 09:32:57	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/formatters/formatter.rb:78:in `pretty_format'
10-Apr-2015 09:32:57	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/printer.rb:15:in `pretty_print'
10-Apr-2015 09:32:57	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/bin/xcpretty:80:in `block in <top (required)>'
10-Apr-2015 09:32:57	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/bin/xcpretty:79:in `each_line'
10-Apr-2015 09:32:57	        from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/bin/xcpretty:79:in `<top (required)>'
10-Apr-2015 09:32:57	        from /usr/bin/xcpretty:23:in `load'
10-Apr-2015 09:32:57	        from /usr/bin/xcpretty:23:in `<main>'
```

Had this happening again on **Bamboo**.

Solved by adding this to our script steps:

```bash
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
```

**Comment by levigroker** [comment]
I also am seeing this. Xcode 6.3.

	/Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/parser.rb:348:in `===': invalid byte sequence in US-ASCII (ArgumentError)
		from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/parser.rb:348:in `update_test_state'
		from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/parser.rb:245:in `parse'
		from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/formatters/formatter.rb:78:in `pretty_format'
		from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/lib/xcpretty/printer.rb:15:in `pretty_print'
		from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/bin/xcpretty:80:in `block in <top (required)>'
		from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/bin/xcpretty:79:in `each_line'
		from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.8/bin/xcpretty:79:in `<top (required)>'
		from /usr/bin/xcpretty:23:in `load'
		from /usr/bin/xcpretty:23:in `<main>'

Adding the exports mentioned seems to have fixed the issue, but... feels like xcpretty should "do the right thing" without these exports.

**Comment by mokagio** [comment]
Thanks @Ashton-W :smile:

**Comment by supermarin** [comment]
@levigroker unfortunately it's not an `xcpretty` thing, I'm pretty sure it's on Ruby / Regex level.
Anyways, machines should be UTF8 by default.

**Comment by levigroker** [comment]
@supermarin Thanks for the reply. Interestingly enough, the only environment variable (of those mentioned) set by default is `LANG=en_US.UTF-8` for me. Shouldn't xcpretty set these to what it needs to prevent this kind of error from occurring?

**Comment by supermarin** [comment]
Pretty sure not because by the time `xcpretty` is loaded, the `ruby` process is loaded already without the ENV set.
