### ISSUE TITLE
Are swift projects supported ?

### ISSUE THREAD

**Issue by xfreebird** [supermarin/xcpretty#140]
Hi,

Does xcpretty support swift projects ? Because currently I don't see any information related to the swift files compilations.

Thanks !

**Comment by kylef** [comment]
@xfreebird xcpretty is not language specific, it just formats the output of xcodebuild. Therefore Swift is certainly not a problem.

**Comment by xfreebird** [comment]
Thanks !  The thing is that in output I can't see messages related to the .swift files, only for .m and .mm

**Comment by kylef** [comment]
I didn't notice the compilation output, made a pull request for this at #142.

**Comment by xfreebird** [comment]
Thanks ! :) hope it will get merged soon !

În data de vineri, 8 mai 2015, Kyle Fuller <notifications@github.com> a
scris:

**Comment by xfreebird** [comment]
Hi, did that merge request entered into release 0.1.10 ? Because I still can't see prettified output for swift files in projects with swift.

**Comment by digitaliceltd** [comment]
I dont think it made it into 0.1.10, however it is in master. Currently tryign to work out how to build from source. Anyone any ideas?

Or can someone give an idea as to when we will see a new xcpretty release?

**Comment by supermarin** [comment]
@digitaliceltd it's released
