### ISSUE TITLE
Got no output when running on GitLab CI

### ISSUE THREAD

**Issue by cybertk** [supermarin/xcpretty#144]
I add xcpretty to filter xcodebuild output which is running on GitLab CI, but when I pipe the output of `xcodebuiild` to `xcpretty`, it will output nothing.

**Comment by kattrali** [comment]
Hi, can you post the version used (`xcpretty -v`) and perhaps a (redacted?) portion of your xcodebuild logs, in case there is something out of the ordinary?

**Comment by cybertk** [comment]
```
$ xcpretty -v
0.1.8
```

xcodebuild output nothing a word, but when I run `xcodebuild | xcpretty` in terminal directly, I can get the right output.

**Comment by supermarin** [comment]
Not an xcpretty issue
