### ISSUE TITLE
SwiftCompile

### ISSUE THREAD

**Issue by digitaliceltd** [supermarin/xcpretty#148]
When our project xcodebuild commands are piped through xcpretty, it hangs when SwiftCompile steps are executing giving the impression that the last non swiftcompile step has froze. Has anyone else experienced this or know how to fix this? Or is it related to one of the open issues?

Thanks

**Comment by argon** [comment]
It appears that xcpretty does not handle the case of compiling Swift files. It may be a change in Xcode 7 but Swift compilation steps begin with `CompileSwift` while it appears that xcpretty only checks for `CompileC`

**Comment by supermarin** [comment]
@digitaliceltd @argon it's fixed in the new release.
