### ISSUE TITLE
Compiling with Opal

### ISSUE THREAD

**Issue by gausie** [supermarin/xcpretty#154]
It would be very useful to be able to use this gem in a Javascript environment. Has anyone messed around with compiling it using Opal?

**Comment by supermarin** [comment]
What would be the use-case for this?

**Comment by gausie** [comment]
I have a NodeJS build server for iOS (http://github.com/gausie/ios-builder). I would really like to use xcpretty to parse the output from xcodebuild into JSON.

**Comment by gausie** [comment]
I don't think this will work unfortunately because Opal doesn't have a Javascript porting of shellwords yet!

**Comment by supermarin** [comment]
Ruby is just an implementation detail that people shouldn't care about.
If your script can use `xcodebuild`, it can use `xcpretty` as well (through the pipe).
