### ISSUE TITLE
xcpretty doesn't show "Check dependencies", "CpResource", "GenerateDSYMFile" steps, etc

### ISSUE THREAD

**Issue by ANTARESXXI** [supermarin/xcpretty#162]
Can I somehow enable print of GenerateDSYMFile (and other significant) step? I'm building large project where GenerateDSYMFile step lasts about 4-5 minutes. And xcpretty stucks on

▸ Compiling SomeFile.cpp

but in fact it waits for GenerateDSYMFile, but doesn't print anything about it (while xcodebuild does).

It's not obvious, especially on Jenkins jobs, and it confuses our team members.

**Comment by supermarin** [comment]
@ANTARESXXI thanks for reporting.

Would you mind writing a test and support for this feature?
It should be fairly trivial if you take a look at the existing ones in `parser.rb` and `parser_spec.rb`.

**Comment by chipp** [comment]
I found that "Check Dependencies" wasn't implemented in simple formatter and I fixed this in my PR.
"CpResource" and "GenerateDSYMFile" outputs in current version:
```
▸ Copying SimpleAuth/Pod/Resources/en.lproj
▸ Generating 'applicant.app.dSYM'
```
