### ISSUE TITLE
xcpretty/parser.rb:358:in `===': invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by ANTARESXXI** [supermarin/xcpretty#164]
xcodebuild works fine for me, but fails after adding | xcpretty -c; exit ${PIPESTATUS[0]

/Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.12/lib/xcpretty/parser.rb:358:in '===': invalid byte sequence in US-ASCII (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.12/lib/xcpretty/parser.rb:358:in 'update_test_state'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.12/lib/xcpretty/parser.rb:253:in 'parse'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.12/lib/xcpretty/formatters/formatter.rb:79:in 'pretty_format'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.12/lib/xcpretty/printer.rb:15:in 'pretty_print'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.12/bin/xcpretty:80:in 'block in \<top (required)\>'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.12/bin/xcpretty:79:in 'each_line'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.12/bin/xcpretty:79:in '\<top (required)\>'
	from /usr/bin/xcpretty:23:in 'load'
	from /usr/bin/xcpretty:23:in '\<main\>'

**Comment by mfrawley** [comment]
Having this too

**Comment by thelvis4** [comment]
Same problem to me in Jenkins while connected over SSH.

**Comment by xfreebird** [comment]
@thelvis4  If you are using Jenkins with SSH in user UI session, then:

```shell
echo "export LC_CTYPE=en_US.UTF-8" >> ~/.profile
``
then restart the SSH agent.
Otherwise configure the Jenkins Salve with the ```LC_CTYPE= en_US.UTF-8" ``` env variable.

**Comment by mfrawley** [comment]
@xfreebird thanks for the tip, will try I was already setting:
export LANG=en_US.UTF-8 but it seemingly had no effect

**Comment by thelvis4** [comment]
@xfreebird thanks! Unfortunately, that didn't work for me.
Worth to mention that I use the [customsshd](https://github.com/xfreebird/customsshd). Btw, thanks for it! 
Do you think the `customsshd` could cause this issue?

Steps I took:
* Update the ruby version to `ruby 2.2.1p85` now.
* Install the `customsshd` as per instructions. Previously, it was installed manually.
* Add `LC_CTYPE=en_US.UTF-8` to `~/.profile`
* `echo "source ~/.profile" >> /Users/jenkins/.bash_profile` while updating ruby it suggested me to do so.
* Restart the slave.

Any clues how can we resolve the issue?

**Comment by xfreebird** [comment]
Hi @thelvis4 , ```customsshd``` just uses standard environment variables provided by the system and overridden by ``` ~/.profile```. 
Have you tried restarting the ```customsshd``` daemon, or even a machine reboot ?

**Comment by thelvis4** [comment]
@xfreebird Ok, i see. Yes, the machine was rebooted, but the issue is still there.
Adding `LC_CTYPE=en_US.UTF-8` to `~/.profile` doesn't work for me.

**Comment by xfreebird** [comment]
@thelvis4 Have you tried enforcing globally in Jenkins settings ?

![](https://cloud.githubusercontent.com/assets/28851/9807026/6c9aaf8c-580a-11e5-8be9-e0ed7ed7ce56.png)

**Comment by thelvis4** [comment]
@xfreebird Enforcing env variables in Jenkins worked just fine. Thanks a lot!

**Comment by ANTARESXXI** [comment]
@xfreebird nice!

**Comment by fabioknoedt** [comment]
For Bamboo I had to do the same as @xfreebird:

<img width="1099" alt="screen shot 2016-05-17 at 15 37 30" src="https://cloud.githubusercontent.com/assets/5463775/15324148/8cb0ee30-1c45-11e6-9212-fa5e29a71c3b.png">

**Comment by enolik97** [comment]
![Screenshot 2019-05-20 at 17 42 47](https://user-images.githubusercontent.com/33845605/58034393-c8d6ba00-7b26-11e9-9bb6-6de60b66b465.png)
Same in gitlab
