### ISSUE TITLE
Jenkins result code issue

### ISSUE THREAD

**Issue by DenTelezhkin** [supermarin/xcpretty#17]
So, i'm trying to integrate XCPretty with my Jenkins setup, and i ran into following issue.

I'm using custom shell command to execute unit tests and if tests succeed - build ipa and upload application to Jenkins. When test fail without xcpretty, build stops there and fails - just like it should. However, with XCPretty Jenkins assumes that build step was successful, even if output prints out that some tests failed. And it goes on and builds ipa and uploads it to TestFlught successfully, which, of course, it should not do.

Here's my xcodebuild command:

``` shell
xcodebuild clean test -scheme MyScheme -workspace MyProject.xcworkspace -destination "name=iPhone Retina (4-inch),OS=7.0" 
```

and here it is with XCPretty:

``` shell
xcodebuild clean test -scheme MyScheme -workspace MyProject.xcworkspace -destination "name=iPhone Retina (4-inch),OS=7.0" | xcpretty -t
```

Maybe i'm missing something?

**Comment by ianfixes** [comment]
Is this workaround still necessary?
