### ISSUE TITLE
Use bundle exec in Rakefile

### ISSUE THREAD

**Issue by 0xced** [supermarin/xcpretty#174]
Shouldn't kick, rspec, cucumber and rubocop be run through bundle exec?

I have rspec 3 installed so when I run `rake spec` I get an error because `be_true` and `be_false` are treated as errors with rspec 3.

It works fine when run through `bundle exec` (with a deprecation warning).

**Comment by kattrali** [comment]
Thanks! :candy:

**Comment by 0xced** [comment]
If I run `rake spec` I still get failures because rspec 3.3.2 is used.
If I run `bundle exec rake spec` everything is fine because it uses the bundled rspec 2.99.2 instead.

Is running rake through `bundle exec` the de facto standard for ruby projects? Is it too obvious to warrant a mention in the README?

**Comment by 0xced** [comment]
And now I just [learnt about rubygems-bundler](http://stackoverflow.com/questions/6588674/what-does-bundle-exec-rake-mean/23668446#23668446) and I’m even more confused. 😕

**Comment by kattrali** [comment]
What on earth... :fearful: That rabbit hole is just too deep, @0xced! Taking another look.
