### ISSUE TITLE
Show only errors

### ISSUE THREAD

**Issue by revolter** [supermarin/xcpretty#175]
Is there any possibility to only print errors and not warnings or build steps?

**Comment by supermarin** [comment]
Yes, if you fix your warnings

**Comment by revolter** [comment]
That was both insulting and funny at the same time. :joy:
Firstly, I am on a big old project, alone, and I don't have time to fix all the warnings (even if I want it so much)
Second, some of the warnings come from 3rd party libraries, sadly.
But I guess I'll take your answer as a no. :cry:

**Comment by supermarin** [comment]
Sorry, I did go for some humor.

The fastest thing you can try is to run `xcpretty` with `--test` flag, or `-t` in shorter.
This would just print dots so your log will be much shorter.

If that doesn't work, you'll most likely need to extend the `simple_formatter` and provide it as your own [`xcpretty` plugin](https://github.com/kattrali/xcpretty-travis-formatter).

**Comment by revolter** [comment]
No problem, I did have a good laugh!

Thank you for the flag tip and the extending directions. I'm gonna' take a look into those.

Did you consider writing a man page?

**Comment by supermarin** [comment]
@revolter not yet, altho it's a great idea.

If you want to contribute, that'd be greatly appreciated1

**Comment by jasongaare** [comment]
@revolter I'm looking into the same thing. Using libs with lots of warnings, would only like to see errors. Did you ever end up writing an extension?

**Comment by revolter** [comment]
Sadly, no :( I could help test and/or contribute if you decide to start it.

**Comment by ianfixes** [comment]
Fix contributed in #345
