### ISSUE TITLE
NoMethodError for JUnit reporter in 0.2.0

### ISSUE THREAD

**Issue by ikesyo** [supermarin/xcpretty#184]
> /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.0/lib/xcpretty/parser.rb:327:in `parse': undefined method `format_ld_warning' for #<XCPretty::JUnit:0x007fd423d89420> (NoMethodError)

See the failed build: https://circleci.com/gh/ikesyo/Himotoki/155

**Comment by daneov** [comment]
Affects me as well : 
`/usr/local/rvm/gems/ruby-2.2.3@global/gems/xcpretty-0.2.0/lib/xcpretty/parser.rb:327:in `parse': undefined method `format_ld_warning' for #<XCPretty::HTML:0x007fd398d32c28> (NoMethodError)`

**Comment by ikesyo** [comment]
Fixed by #187.
