### ISSUE TITLE
Invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by RLovelett** [supermarin/xcpretty#190]
When running my test step `xcpretty` is dying. Is this what I should be using the flag `--no-utf` for? I've tried adding that flag to my command to no avail.

Summary of the failure below.

```
$ xcodebuild build -workspace RefmanContentBundleTools.xcworkspace -scheme RefmanContentBundleTools -destination 'platform=iOS Simulator,name=iPad Air,OS=9.0' test | xcpretty --no-utf -c && exit ${PIPESTATUS[0]}
...
All tests
Test Suite TestSuite.xctest started
ImporterTests
    . testImportNonExistingFile (0.029 seconds)
    . testNotAZipArchive (0.014 seconds)
    . testSample (0.001 seconds)
    . testSamplePasswordDoesNotMatchBundle (0.116 seconds)
    . testSampleWithInvalidContentSignature (0.323 seconds)
    . testSampleWithMalformedJSON (0.111 seconds)
    . testSampleWithMissingRequiredTTGSupportProperty (0.140 seconds)
    . testSampleWithoutPassword (0.011 seconds)
    . testSampleWithoutTTGSupport (0.106 seconds)
/Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.1/lib/xcpretty/parser.rb:383:in `===': invalid byte sequence in US-ASCII (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.1/lib/xcpretty/parser.rb:383:in `update_test_state'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.1/lib/xcpretty/parser.rb:270:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.1/lib/xcpretty/formatters/formatter.rb:83:in `pretty_format'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.1/lib/xcpretty/printer.rb:15:in `pretty_print'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.1/bin/xcpretty:80:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.1/bin/xcpretty:79:in `each_line'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.1/bin/xcpretty:79:in `<top (required)>'
	from /usr/bin/xcpretty:23:in `load'
	from /usr/bin/xcpretty:23:in `<main>'

ERROR: Build failed with: exit status 1
```

If it matters I'm using Xcode Version 7.1 (7B91b).

**Comment by jasperblues** [comment]
Every now and then I get this as well. Besides finding the root cause and fixing this, how about: 

- Instead of crashing, flush valid output, log a warning and move on. 

This way any xcpretty projects set up on the build server won't fail the whole build. 
Less maintenance overhead to remove xcpretty in order to restore the build to working condition.

**Comment by igrekde** [comment]
I'm facing this issue too.

**Comment by xfreebird** [comment]
Add ```export LC_ALL=en_US.UTF-8```, to ```~/.profile``` and ```~/.bashrc```

**Comment by RLovelett** [comment]
@xfreebird my typical user's profile did have those set for the environment. I was experiencing this while running on GitLab runner. Adding these to the `.gitlab-ci.yml` did solve the immediate problem. So thank you for this work-around.

However, I cannot help but feel that @jasperblues suggestion should be considered. I agree that `xcpretty` should not cause a build to fail regardless of whether it can properly format the output.

**Comment by jasperblues** [comment]
#122

**Comment by Apocryphon** [comment]
Also running into this issue with Jenkins, on Xcode 7.2.

**Comment by achansonjr** [comment]
Hi @supermarin I work with @RLovelett and we have re-encountered this issue again. Here is the logfile output you requested.
[outputfile.txt](https://github.com/supermarin/xcpretty/files/141425/outputfile.txt)

**Comment by ReDetection** [comment]
Have this issue now, 100% reproducible. Recent cocoapods release 1.0.0 use 📦 char to mark it's build phases. So in GitLab-CI runner this leads to xcpretty explode with `Invalid byte sequence in US-ASCII` error.

**Comment by geekyfox90** [comment]
Having the same issue, if you want ever my logs I'm here 👍

**Comment by dhoskins** [comment]
Also seeing this as part of my fastlane/scan/Jenkins setup.  I have tried every conceivable method of setting `LANGUAGE`, `LANG` and `LC_ALL` to `en_US.UTF-8` (added to `.bashrc` and `.profile`, `export`ing them manually in the build config, and tried setting them globally for the node as suggested [here](https://github.com/supermarin/xcpretty/issues/164#issuecomment-144696595)) and still getting this error.

**Comment by dhoskins** [comment]
Wow.  Setting it in `.bash_profile` finally solved it.

Ensuring the command `locale` outputs

    LC_ALL="en_US.UTF-8"

is important.  Also `en_GB.UTF-8` will not work, seems it must be `en_US`.

**Comment by farshidce** [comment]
i was also able to get pass this error by adding the export statement to the gitlab ci script before running any of the xcodebuild commands. I did not want to rely on .bash_profile because i didn't want to assume the bash_profile is correct in all the build slaves.
- script:
  - export LC_ALL=en_US.UTF-8
but as mentioned above it is best that xcpretty not fail the build when it is unable to format it.

**Comment by perforator85** [comment]
I had the same issue today.
In our jenkins build job we had to add "export LC_CTYPE=en_US.UTF-8" before triggering the xcodebuild.

**SOLUTION:**
```
#!/bin/bash -l -e
echo "xcodebuild and archive ..."
export LC_CTYPE=en_US.UTF-8
xcodebuild -scheme "MyApp" | tee "xcodebuild.log" | xcpretty && exit ${PIPESTATUS[0]}
```
