### ISSUE TITLE
Custom Reporter

### ISSUE THREAD

**Issue by mtitolo** [supermarin/xcpretty#199]
Just like custom formatters can be specified by a command line flag, custom reporters should be able to as well. The 3 provided are a great start, but creating custom ones will allow xcpretty to hook up with more services, especially ones that use an API and expect a certain output.

**Comment by mtitolo** [comment]
I have the bandwidth to work on this, but would like to get some input on design. From looking at the way reporters are currently implemented, I see two ways this can go.

Option 1: Mimic the FormatMethods module and expect all custom reporters to implement all methods (which is unfortunately not enforceable):
```
module ReporterMethods
	EMPTY = ''.freeze
	def handle(line);						EMPTY; end
	def finish;								EMPTY; end
	def write_report_file; 					EMPTY; end
	def initialize(options);					EMPTY; end
	def handle(line); 						EMPTY; end
end
```

Option 2: Since Reporters are basically Formatters that write to disk, create a Reporter class that inherits from Formatter, adding a `write_report_file` method. 

Also this can work with the existing reporter flag by adding a simple check whether `FORMAT` is one of the build-in reporter formats, and if not load the reporter from disk just like with Formatters.

**Comment by kattrali** [comment]
Thanks for the suggestion, @mtitolo. This sounds useful. Option 2 seems like the least error-prone option, and should work best with the existing reporter flag, as you mentioned. If you have the time to start on it, I have the bandwidth to add some input. :)

**Comment by mtitolo** [comment]
Is there a strong opinion as to what format the base class prints out to? I was thinking either a simple JSON list or a plaintext representation of the data. JSON is also nice since it's easier to test against.

**Comment by kattrali** [comment]
I don't think so, either one sounds nice to me.

**Comment by mtitolo** [comment]
For simplicity I went with plaintext. I've been doing this on work time so there's a little process that has to happen before I can open a PR but I do have it working :)

**Comment by kattrali** [comment]
Awesome!

**Comment by supermarin** [comment]
> For simplicity I went with plaintext.

:+1: :+1:

**Comment by shalinbshah** [comment]
if we can have report in format of cucumber json it will be great because then we can integrate XCTest reports to multiple Test Management Tools
