### ISSUE TITLE
Using xcpretty with xcodebuild when running tests does not return shell console on completion

### ISSUE THREAD

**Issue by jinjorge** [supermarin/xcpretty#205]
xcpretty v0.2.2 (tested as far back as v0.1.7 and observed the issue was in all releases including 0.1.7)
ruby v2.2.1
Xcode v7.2.1
OS X 10.11.4

when using `xcpretty` with `xcodebuild` to run UI tests, when the testing completes, the session hangs and one has to ctrl-c to recover the shell console.

Running the same `xcodebuild` command without `xcpretty` returns the shell console when the testing completes.

Found this issue when using Fastlane's Scan to run UI tests. Added a note to https://github.com/fastlane/scan/issues/49 initially suspecting that this was a Scan issue though I looks to be an issue with xcpretty.

here's the `xcodebuild` command that I am running

```
set -o pipefail && xcodebuild -workspace Myapp.xcworkspace -scheme "Disneyland" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s' test | xcpretty
```

```
▸ Check Dependencies
▸ Test Succeeded
All tests
Test Suite MysteryHouse Tests.xctest started
Login
    ✓ testLogIn (10.800 seconds)
    ✓ testLogInCancel (6.333 seconds)
OOBE
    ✓ testActivationBackButton (6.953 seconds)
    ✓ testBadActivationCode (8.421 seconds)
    ✓ testEyefiCardTransfer (13.820 seconds)
    ✓ testImport (13.074 seconds)
Settings
    ✓ testSettings (13.045 seconds)


	 Executed 7 tests, with 0 failures (0 unexpected) in 72.448 (72.455) seconds

^C/Users/jeremiah/.rvm/gems/ruby-2.2.1/gems/xcpretty-0.2.2/bin/xcpretty:79:in `each_line': Interrupt
	from /Users/jeremiah/.rvm/gems/ruby-2.2.1/gems/xcpretty-0.2.2/bin/xcpretty:79:in `<top (required)>'
	from /Users/jeremiah/.rvm/gems/ruby-2.2.1/bin/xcpretty:23:in `load'
	from /Users/jeremiah/.rvm/gems/ruby-2.2.1/bin/xcpretty:23:in `<main>'
	from /Users/jeremiah/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jeremiah/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

➜  MysteryHouse git:(sam/wip/xcode7-take2) ✗
```

**Comment by supermarin** [comment]
Pretty sure this is not an xcpretty issue, but whoever holds the parrent process and pipes to `xcpretty`.

**Comment by Whirlwind** [comment]
I have same problem. I retry it and it is ok. I don't know why it is.

**Comment by pevasquez** [comment]
I know this is closed, but has any of the affected people found out what the problem was? I am facing the same issue
