### ISSUE TITLE
Doesn't work on default ruby shipped with OSX

### ISSUE THREAD

**Issue by jimon** [supermarin/xcpretty#211]
So, xcpretty doesn't work with default ruby shipped with OSX, and to make it work we need rbenv (or something else) and install more up-to-date version of ruby and gems. Which is ok for local setups, and a bit cumbersome for CI setups, especially if our projects are not using ruby at all (let's say C++ or Objective-C). Would be really nice to eliminate such dependency.

What's your opinion on this one?

**Comment by jimon** [comment]
@zjfroot

**Comment by kattrali** [comment]
Hi @jimon, what is the error you are seeing preventing xcpretty from working with system Ruby?

**Comment by jimon** [comment]
Apparently it works on OS X 10.11.4

    export PATH=$PATH:/Users/%usrname%/.gem/ruby/2.0.0/bin
    gem install --user-install xcpretty
    xcpretty

Sorry for trouble!
