### ISSUE TITLE
xcpretty doesn't filter some XCode stuf

### ISSUE THREAD

**Issue by patoroco** [supermarin/xcpretty#213]
Hi,

I'm using `scan` from `fastlane` suite to run our tests, and it's using `xcpretty` by default.

My question is about some stuff which is 'flooding' results, as you can see on the snapshot below:
![screen shot 2016-04-25 at 12 28 15](https://cloud.githubusercontent.com/assets/701909/14781233/9e6079b8-0ae1-11e6-9c1f-7ac53c2fd352.png)

There is any option to filter these lines? Any suggestion? Or simply I'm using in a bad way `xcpretty` 🍡 ?

**Comment by revolter** [comment]
I have the same problem. The logs are from plugins as far as I understood.

**Comment by supermarin** [comment]
This is STDERR output, which doesn't go through pipes
