### ISSUE TITLE
xcpretty exits when running without any options

### ISSUE THREAD

**Issue by minwoolee** [supermarin/xcpretty#214]
xcpretty behaves different from other Unix commands (grep, tee, wc, ... ) that it exits with help message as soon as it launches, which prevents it from being spawned and pipe stdin to it programmatically. Is there any workaround to this? Thanks.

**Comment by supermarin** [comment]
@minwoolee there is no workaround - the bin file (bin/xcpretty) needs to be patched to support this. I believe it's a very quick fix.

@kattrali any objections?

**Comment by kattrali** [comment]
None.

**Comment by supermarin** [comment]
Will be released In the next version
