### ISSUE TITLE
exit 0 when test failed

### ISSUE THREAD

**Issue by ooopscc** [supermarin/xcpretty#216]
I make a failed case in purpose. When run without `| xcpretty`, it exist status is not 0, it's 65. But using xcpretty, it always 0 no matter it fails or not.
The command is 
```
xcodebuild -workspace $workspace -scheme $scheme -sdk $sdk -destination $destination test | xcpretty
```
![snip20160501_61](https://cloud.githubusercontent.com/assets/1056803/14940923/78d4838a-0fbc-11e6-8545-15a7be1a5666.png)

**Comment by kattrali** [comment]
Per the [usage instructions](https://github.com/supermarin/xcpretty#usage), you may need to use `pipefail` and check [`pipestatus[1]` (for zsh)](http://unix.stackexchange.com/a/14276) to get the exit status of the running process.

**Comment by ooopscc** [comment]
Thanks. Sorry for not pay attention to that README.
