### ISSUE TITLE
Trouble getting started developing on OS X

### ISSUE THREAD

**Issue by JonHodgson** [supermarin/xcpretty#233]
Hi,
I'm completely new to ruby (though not to programming in general) and want to create an XCPretty formatter (to generate xml output as it happens).

So, obvious first step is to get it running.

Cloned from github, go to the xcpretty/lib folder

```
Mac-6c4008b5982c:lib jon$ ruby xcpretty.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcpretty/reporters/reporter (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from xcpretty.rb:11:in `<main>'
```

commenting out the line

require 'xcpretty/reporters/reporter'

exits with no reported errors.

I'm guessing I'm missing something basic, being a newbie in the world of ruby?

**Comment by kattrali** [comment]
Hi @JonHodgson, I’d suggest looking at [xcpretty-travis-formatter](https://github.com/kattrali/xcpretty-travis-formatter) for an example of how to start. The xcpretty internals need the entire lib to run, formatters just sit on top of it.

If you want to run xcpretty directly, use `bin/xcpretty`, which handles the library loading.
