### ISSUE TITLE
Suppress output

### ISSUE THREAD

**Issue by revolter** [supermarin/xcpretty#237]
I am using `fastlane` to generate screenshots and my project is quite big, and some of the libraries have quite a few warning, and I would like for it not to show them. Either suppress warnings, either suppress __any__ output except errors, if they occur, and some "Build completed" message. Is this currently possible?

**Comment by revolter** [comment]
Looks like [xcodebuild now supports a -quiet flag to suppress output other than errors and warnings][1].

  [1]: https://developer.apple.com/library/prerelease/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html

Is there any possibility for this flag to be added to `xcpretty`?

**Comment by supermarin** [comment]
You can just add it to the xcodebuild command beforehands. It needs to be added into fastlane if you're not running xcodebuild yourself.

**Comment by revolter** [comment]
Right, sorry!
