### ISSUE TITLE
0.2.3 regression: format_failing_test: undefined method sub for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by jmoody** [supermarin/xcpretty#245]
* Xcode 8
* El Cap
* xcpretty 0.2.3

### Reproduce

```
# Tests should have at least one failure.
xcodebuild < args > | xcpretty -c --report junit && exit ${PIPESTATUS[0]}
```

### Expected

A `junit` report to be generated and no error to be raised.

### Found

```
/Users/moody/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/reporters/junit.rb:56:in `format_failing_test': undefined method `sub' for nil:NilClass (NoMethodError)
        from /Users/moody/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/parser.rb:359:in `parse'
        from /Users/moody/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/reporters/junit.rb:27:in `handle'
        from /Users/moody/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/bin/xcpretty:85:in `block (2 levels) in <top (required)>'
        from /Users/moody/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/bin/xcpretty:85:in `each'
        from /Users/moody/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/bin/xcpretty:85:in `block in <top (required)>'
        from /Users/moody/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/bin/xcpretty:83:in `each_line'
        from /Users/moody/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/bin/xcpretty:83:in `<top (required)>'
        from /Users/moody/.rbenv/versions/2.3.1/bin/xcpretty:23:in `load'
        from /Users/moody/.rbenv/versions/2.3.1/bin/xcpretty:23:in `<main>'
```

### Notes

This does not happen in 0.2.2.

**Comment by supermarin** [comment]
Duplicate, releasing fix in 0.2.4

**Comment by jmoody** [comment]
Apologies.  I did spend some time searching for a duplicate.

Thanks for all your hard work!  `xcpretty` is amazing and essential to our workflow.

**Comment by yas375** [comment]
@supermarin thanks for fixing this so quick! We've also just run into this. Looking forward 0.2.4 👍

**Comment by yas375** [comment]
> Duplicate, releasing fix in 0.2.4

@supermarin I also wasn't able to find where this was reported before. Do you have the fix commited somewhere? I don't see it on `master`. I would be glad to point to a dev version of xcpretty on our CI machine. And can report back to you if the fix solves this problem with `undefined method `sub' for nil:NilClass`. Thanks in advance!

**Comment by supermarin** [comment]
It's the same issue as https://github.com/supermarin/xcpretty/issues/241, introduced here: https://github.com/supermarin/xcpretty/commit/47e4cdf2ce262ebccbdb904c4f687461722fe921

**Comment by yas375** [comment]
@supermarin thanks!

**Comment by supermarin** [comment]
0.2.4 released

**Comment by mrooney** [comment]
Any chance of updating the [changelog](https://github.com/supermarin/xcpretty/blob/master/CHANGELOG.md) for this? We'd love to upgrade but without having any idea of what changed since 0.2.1, it is a little tricky.

**Comment by yas375** [comment]
@mrooney you can easily review changes here: https://github.com/supermarin/xcpretty/compare/v0.2.1...v0.2.4

**Comment by mrooney** [comment]
That's a diff / commit log, not the same as an easily readable summary of
functional changes which many projects maintain. However this indirectly
answers my question, I'm guessing the answer is no :)

On Fri, Nov 4, 2016 at 12:02 PM, Victor Ilyukevich <notifications@github.com

**Comment by yas375** [comment]
> I'm guessing the answer is no

@mrooney I'm not maintainer of this project so ¯\\\_(ツ)\_/¯. I'm just trying to help as I can.

**Comment by supermarin** [comment]
@mrooney that's a good point; before we used to enforce changelog updates on pull requests, and might do the same when 0.3 lands out (which will have it's own clear changelog).

For the minor updates (0.2.1 - 0.2.x) you should be safe to update with no API changes.
By semver, you should assume the patch number updates are mostly bugfixes and improvements.
