### ISSUE TITLE
Please add the latest version to Rubygems.org

### ISSUE THREAD

**Issue by UkuLoskit** [supermarin/xcpretty#252]
Hello!

The latest version 0.2.5 was released 17 days ago, but it is not available via RubyGems.org which still has 0.2.4.

Could you please update this?

Thanks so much!

**Comment by supermarin** [comment]
@UkuLoskit it didn't contain that much,  and broke integration tests. I need to fix that first, then it'll come out

**Comment by supermarin** [comment]
as in - 0.2.4 is almost identical
