### ISSUE TITLE
xcpretty hide symbol(s) not found error

### ISSUE THREAD

**Issue by pengbins** [supermarin/xcpretty#255]
```
> xcpretty --version
0.2.4
```
output by xcodebuild
```
> xcodebuild
.....
Undefined symbols for architecture armv7:
  "std::rethrow_exception(std::exception_ptr)", referenced from:
      BLYCPPExceptionTerminate() in Bugly(libBugly.a-armv7-master.o)
  "std::current_exception()", referenced from:
      BLYCPPExceptionTerminate() in Bugly(libBugly.a-armv7-master.o)
  "std::exception_ptr::exception_ptr(std::exception_ptr const&)", referenced from:
      BLYCPPExceptionTerminate() in Bugly(libBugly.a-armv7-master.o)
  "std::exception_ptr::~exception_ptr()", referenced from:
** BUILD FAILED**
The following build commands failed:
	Ld build/XXXXX  normal arm64
(1 failure)
```

output parsed by xcpretty didn't show the symbol which can't be found and the reference that caused failure
```
> xcodebuild  | xcpretty
▸ Building KSYLiveDemo/KSYLiveDemo [(Release)]
▸ Check Dependencies
▸ Linking KSYLiveDemo
❌  ld: symbol(s) not found for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
▸ Linking KSYLiveDemo
** BUILD FAILED **
The following build commands failed:
	Ld build/XXXXX normal arm64
(1 failure)
```

**Comment by supermarin** [comment]
Will be fixed in 0.3

**Comment by darkforestzero** [comment]
when's 0.3 coming?  love xcpretty, but this is an annoying issue

**Comment by supermarin** [comment]
@darkforestzero sorry about that, I have a full time job that takes 110% of my energy and it makes it hard to progress with speed.

You can try using the `blacklist` branch, it's fairly usable by now. The errors aren't nicely parsed and formatted, but they are spit out and you will see them. Let me know if you have any trouble with that.

**Comment by wtlucky** [comment]
@supermarin Now the newest version was 0.2.8, do it fix this issue?

**Comment by WeijunDeng** [comment]
I fixed it without changing xcpretty.
see
https://dengweijun.com/fix-hidden-undefined-symbols-using-xcpretty
https://github.com/WeijunDeng/xcpretty_fix
