### ISSUE TITLE
Permission denied - /Library/Ruby/Gems/2.0.0/gems/rouge-1.11.1/Gemfile

### ISSUE THREAD

**Issue by loveace** [supermarin/xcpretty#257]
em install xcpretty
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /Library/Ruby/Gems/2.0.0/gems/rouge-1.11.1/Gemfile

This happened to me. How to resolve it？

**Comment by supermarin** [comment]
`sudo gem install xcpretty`
