### ISSUE TITLE
Failing to install/update

### ISSUE THREAD

**Issue by FranciscoAmado** [supermarin/xcpretty#258]
Hi there! 

I was trying to update `fastlane` and got an error trying to update `xcpretty`.
As so, I tried to install/update `xcpretty` and got the same error: `no implicit conversion of nil into String`

I'll leave the full output here in case you find it useful

<details><summary><b>gem install output</b></summary>
~ sudo gem install xcpretty --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=xcpretty
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/api/v1/dependencies?gems=rouge
200 OK
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/.gitignore
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/.hound.yml
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/.kick
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/.rubocop.yml
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/.travis.yml
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/CHANGELOG.md
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/CONTRIBUTING.md
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/Gemfile
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/LICENSE.txt
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/README.md
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/Rakefile
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/assets/report.html.erb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/bin/xcpretty
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/assets/RACCommandSpec, line 80, hello xcpretty.png
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/assets/apple_raw.png
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/custom_formatter.feature
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/custom_reporter.feature
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/fixtures/xcodebuild.log
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/html_report.feature
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/json_compilation_database_report.feature
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/junit_report.feature
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/knock_format.feature
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/simple_format.feature
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/steps/custom_reporter_steps.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/steps/formatting_steps.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/steps/html_steps.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/steps/json_steps.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/steps/junit_steps.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/steps/report_steps.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/steps/xcpretty_steps.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/support/env.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/tap_format.feature
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/test_format.feature
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/features/xcpretty.feature
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/ansi.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/formatters/formatter.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/formatters/knock.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/formatters/rspec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/formatters/simple.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/formatters/tap.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/parser.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/printer.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/reporters/html.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/reporters/json_compilation_database.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/reporters/junit.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/reporters/reporter.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/snippet.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/syntax.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/term.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/lib/xcpretty/version.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/fixtures/NSStringTests.m
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/fixtures/constants.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/fixtures/custom_formatter.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/fixtures/custom_reporter.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/fixtures/oneliner.m
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/fixtures/raw_kiwi_compilation_fail.txt
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/fixtures/raw_kiwi_fail.txt
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/fixtures/raw_specta_fail.txt
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/spec_helper.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/support/matchers/colors.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/xcpretty/ansi_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/xcpretty/formatters/formatter_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/xcpretty/formatters/rspec_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/xcpretty/formatters/simple_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/xcpretty/parser_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/xcpretty/printer_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/xcpretty/reporters/junit_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/xcpretty/reporters/reporter_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/xcpretty/snippet_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/xcpretty/syntax_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/spec/xcpretty/term_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.4/xcpretty.gemspec
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
</details>

Any idea how to work around this, please?

Thanks for `xcpretty`! It's awesome!
Francisco

**Comment by KrauseFx** [comment]
It seems like this issue isn't fastlane or xcpretty related, but something with the `gem` command. If you want to use `xcpretty` as part of _fastlane_, check out our new [bundled fastlane](https://download.fastlane.tools), which bundles _fastlane_, `xcpretty` and all other dependencies 👍

**Comment by FranciscoAmado** [comment]
Thanks for the tip! 👍🏻 I'll remove and update as is then 😄 Closing this now
