### ISSUE TITLE
Throws invalid byte sequence error

### ISSUE THREAD

**Issue by gbonda** [supermarin/xcpretty#261]
Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/lib/xcpretty/parser.rb:422:in `===': invalid byte sequence in US-ASCII (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/lib/xcpretty/parser.rb:422:in `update_test_state'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/lib/xcpretty/parser.rb:299:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/lib/xcpretty/formatters/formatter.rb:87:in `pretty_format'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/lib/xcpretty/printer.rb:19:in `pretty_print'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/bin/xcpretty:84:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/bin/xcpretty:83:in `each_line'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.4/bin/xcpretty:83:in `<top (required)>'
	from /usr/local/bin/xcpretty:23:in `load'
	from /usr/local/bin/xcpretty:23:in `<main>'

**Comment by elstntho** [comment]
Pls check this: https://github.com/supermarin/xcpretty/issues/190
