### ISSUE TITLE
Operation not permitted - /usr/bin/rougify

### ISSUE THREAD

**Issue by Detailscool** [supermarin/xcpretty#264]
I can't find any files called rougify in /usr/bin/ directory .In the same time, I've already got the latest version of Ruby and used sudo mode.

**Comment by jasef** [comment]
Can't verify right now, but it could potentially be related to this: https://github.com/jneen/rouge/blob/master/bin/rougify.

**Comment by supermarin** [comment]
@jasef thanks for that! @Detailscool it seems like you have some kind of a permission issue.
Try uninstalling both xcpretty and rouge and reinstalling xcpretty.
