### ISSUE TITLE
xcpretty not logging Compiling file.swift in main project

### ISSUE THREAD

**Issue by szweier** [supermarin/xcpretty#266]
It appears as though the compiling step for swift files within the actual project are not being logged.  I do however see the `Compiling class.swift` message printed for swift files within libraries I've imported.

**Comment by supermarin** [comment]
Do you have whole module optimization on?

**Comment by szweier** [comment]
This was being run through fast lane's gym tools, it seems to just pipe into xcpretty.

**Comment by szweier** [comment]
Just what I was looking for thank you.
