### ISSUE TITLE
Support for ruby 1.9 dropped?

### ISSUE THREAD

**Issue by jugutier** [supermarin/xcpretty#267]
When trying to install there is an error with ruby 1.9

Nothing in the (changelog)[https://github.com/supermarin/xcpretty/blob/master/CHANGELOG.md] indicates that support was dropped after 0.0.2 when it was introduced.

Console output:

```shell

~ $ gem install xcpretty
Fetching: rouge-1.11.1.gem (100%)
Fetching: xcpretty-0.2.4.gem (100%)
ERROR:  Error installing xcpretty:
	xcpretty requires Ruby version >= 2.0.0.
~ $ ruby --version
ruby 1.9.3p545 (2014-02-24 revision 45159) [x86_64-darwin12.5.0]
~ $ sw_vers -productVersion
10.10.5

```

**Comment by supermarin** [comment]
@jugutier sorry about that, we've been bad about maintaining a proper changelog.
We've dropped < 2.0 support when 2.0 became the default system ruby on OSX.

**Comment by jugutier** [comment]
What's the last version that would support 1.9?

**Comment by supermarin** [comment]
it looks like right before we did a major version bump to 0.2.

https://github.com/supermarin/xcpretty/commit/91c766f4c82541564297e958254ba5d920166cf5

**Comment by supermarin** [comment]
So `gem xcpretty, '~> 0.1.0'`

**Comment by jugutier** [comment]
`gem install xcpretty` wasn't able to find a version that would work with 1.9 automatically, is this because ruby.version wasn't specified in your spec file?

I should be set with this anyways. Thanks

**Comment by supermarin** [comment]
It was specified indeed https://github.com/supermarin/xcpretty/commit/91c766f4c82541564297e958254ba5d920166cf5
