### ISSUE TITLE
attach screenshots to failed test, not to the suite

### ISSUE THREAD

**Issue by aditjain** [supermarin/xcpretty#278]
| xcpretty --report html --screenshots

So I am able to attach screenshot to the failing suite. But its not as neat as i thought it would be. 

My testsuite has multiple test methods. And out of 3 test 2 failed and 1 passed. --screenshots shows screenshot at the top of suite and does not clearly tell which screenshot belong to which failed test. Is there a way to append screenshot right below or above "each" failed test? 

please let me know.
<img width="649" alt="screen shot 2017-04-24 at 11 43 28 am" src="https://cloud.githubusercontent.com/assets/4325607/25353200/4fc9c11c-28e3-11e7-859e-02a7a64d813b.png">

**Comment by supermarin** [comment]
@aditjain thanks for reporting this.
I don't have bandwidth ATM to look into this, but @mattcotton was working on this recently

**Comment by aditjain** [comment]
@supermarin Thanks for the response! 

@mattcotton can you please help?

**Comment by mattcotton** [comment]
@aditjain I've been working on something similar to this recently. I'll submit a Pull Request soon.

**Comment by aditjain** [comment]
Thanks @mattcotton !! waiting for you PR and get this one resolved. Also, if by any chance if this is not going to happen soon, please let me know so i can look for alternative :) thanks again!!!

**Comment by mattcotton** [comment]
The actual feature is done on my fork, just need to tidy a few things up before I create a pull request.

Requirements are that the screenshot file name begins with the name of the test.

**Comment by aditjain** [comment]
Thanks @mattcotton. 
So instead of naming .png file by testsuite, should i now name them by test method 
or something like <testmethod>.<testSuite>.png?

I believe unique combination will be good since there may be multiple test methods with same name in different testSuites (may be :) ).

**Comment by aditjain** [comment]
@mattcotton did you get a chance to merge this code? please let me know when it is ready to use :)

**Comment by mattcotton** [comment]
@aditjain this is now available on #280. At the moment this requires the screenshot filename to begin with the test method name, however I take your point about the testsuite/method combination being more unique and may add this in future if I get time.

**Comment by aditjain** [comment]
Sweet!! thx @mattcotton

**Comment by mattcotton** [comment]
@aditjain #280 now contains support for screenshots in a `"TESTSUITE_TESTMETHOD"` format (separated by an underscore)

**Comment by aditjain** [comment]
woohoo! you are the best. I will test soon.
