### ISSUE TITLE
xcpretty does not match errors prefixed with "<module-include>"

### ISSUE THREAD

**Issue by seanabraham** [supermarin/xcpretty#282]
As an example, this error line does not get matched anywhere:
`<module-includes>:1:1: error: umbrella header for module 'FooBar' does not include header 'Baz.h`

I'm happy to put up a PR including this, should this be captured by the `COMPILE_ERROR_MATCHER` (with the "file_path" just being `<module-includes>`), elsewhere, or be captured by a new matcher entirely?

**Comment by supermarin** [comment]
Closing in favor of #283
