### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by devKlausS** [supermarin/xcpretty#285]
we receive an argument error
tested versions 0.2.3 0.2.8

`/Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.8/lib/xcpretty/parser.rb:429:in `===': invalid byte sequence in US-ASCII (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.8/lib/xcpretty/parser.rb:429:in `update_test_state'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.8/lib/xcpretty/parser.rb:304:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.8/lib/xcpretty/formatters/formatter.rb:87:in `pretty_format'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.8/lib/xcpretty/printer.rb:19:in `pretty_print'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.8/bin/xcpretty:84:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.8/bin/xcpretty:83:in `each_line'
	from /Library/Ruby/Gems/2.0.0/gems/xcpretty-0.2.8/bin/xcpretty:83:in `<top (required)>'
	from /usr/local/bin/xcpretty:23:in `load'
	from /usr/local/bin/xcpretty:23:in `<main>'`

**Comment by DoDoENT** [comment]
This also happens to me with ruby version `ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]`. However, with version `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]` appears to be working correctly.

**Comment by DoDoENT** [comment]
OK, after more checks, it appers to be related to SSH, not ruby version, i.e. even with ruby 2.4.1p111 it crashes when run via SSH (or from Jenkins).

**Comment by DoDoENT** [comment]
The problem is actually in parsing test output - if test prints unicode characters and xcpretty is run in SSH/Jenkins mode (i.e. in context which does not support unicode), then this crash happens.

**Comment by DoDoENT** [comment]
[This appears](https://stackoverflow.com/a/17031697/213057) to solve the issue.
