### ISSUE TITLE
allow customization of HTML Report filename

### ISSUE THREAD

**Issue by zaxy78** [supermarin/xcpretty#287]
Is there a way to allow a command line argument to customize the report file?
I actually want to give it a timestamp in the name so every run won't override the previous result...

**Comment by mkieselmann** [comment]
+1

**Comment by mattcotton** [comment]
@zaxy78 @mkieselmann - it looks like this is already possible by passing in the `--output` parameter with a path to the report. It's documented in the README at the end of the Reporters section.
