### ISSUE TITLE
test with a fatal error not managed

### ISSUE THREAD

**Issue by kenji21** [supermarin/xcpretty#291]
When a test fails with:  `fatal error: unexpectedly found nil while unwrapping an Optional value`
error is shown with ❌, but is not present in xml output.

Simply created an iOS single view app project in swift, and added to the tests:

````swift
    func testExample() {
        // This is an example of a functional test case.
        // Use XCTAssert and related functions to verify your tests produce the correct results.
    }
    
    func testFatalError() {
        var view: UIView! = nil
        
        view.isHidden = false
    }
````

I think this is related to xcodebuild restarting tests when one fail:

````
Test Suite 'All tests' started at 2017-07-10 15:01:12.049
Test Suite 'xcprettyFatalErrorTests.xctest' started at 2017-07-10 15:01:12.049
Test Suite 'xcprettyFatalErrorTests' started at 2017-07-10 15:01:12.049
Test Case '-[xcprettyFatalErrorTests.xcprettyFatalErrorTests testExample]' started.
Test Case '-[xcprettyFatalErrorTests.xcprettyFatalErrorTests testExample]' passed (0.001 seconds).
Test Case '-[xcprettyFatalErrorTests.xcprettyFatalErrorTests testFatalError]' started.
fatal error: unexpectedly found nil while unwrapping an Optional value

Restarting after unexpected exit or crash in xcprettyFatalErrorTests/testFatalError(); summary will include totals from previous launches.

Test Suite 'Selected tests' started at 2017-07-10 15:01:17.698
Test Suite 'xcprettyFatalErrorTests.xctest' started at 2017-07-10 15:01:17.698
Test Suite 'xcprettyFatalErrorTests' started at 2017-07-10 15:01:17.699
Test Case '-[xcprettyFatalErrorTests.xcprettyFatalErrorTests testPerformanceExample]' started.
/Users/kenji/Desktop/xcprettyFatalError/xcprettyFatalErrorTests/xcprettyFatalErrorTests.swift:40: Test Case '-[xcprettyFatalErrorTests.xcprettyFatalErrorTests testPerformanceExample]' measured [Time, seconds] average: 0.000, relative standard deviation: 174.575%, values: [0.000005, 0.000001, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000], performanceMetricID:com.apple.XCTPerformanceMetric_WallClockTime, baselineName: "", baselineAverage: , maxPercentRegression: 10.000%, maxPercentRelativeStandardDeviation: 10.000%, maxRegression: 0.100, maxStandardDeviation: 0.100
Test Case '-[xcprettyFatalErrorTests.xcprettyFatalErrorTests testPerformanceExample]' passed (0.258 seconds).
Test Suite 'xcprettyFatalErrorTests' failed at 2017-07-10 15:01:17.957.
	 Executed 3 tests, with 1 failure (0 unexpected) in 0.258 (0.259) seconds
Test Suite 'xcprettyFatalErrorTests.xctest' failed at 2017-07-10 15:01:17.958.
	 Executed 3 tests, with 1 failure (0 unexpected) in 0.258 (0.259) seconds
Test Suite 'Selected tests' failed at 2017-07-10 15:01:17.958.
	 Executed 3 tests, with 1 failure (0 unexpected) in 0.258 (0.260) seconds
````

[xcodebuild.log.txt](https://github.com/supermarin/xcpretty/files/1135552/xcodebuild.log.txt)

[tests.xml.txt](https://github.com/supermarin/xcpretty/files/1122531/tests.xml.txt)

Forgot to mention version used : 0.2.8

**Comment by kenji21** [comment]
Test feature added (and failing):
https://travis-ci.org/openium/xcpretty/jobs/252003585

**Comment by kenji21** [comment]
Ok, fixed them in https://travis-ci.org/openium/xcpretty/builds/252026938

The PR is the 293

**Comment by kenji21** [comment]
The `restarting after unexpected exit or crash` message can also be encountered when using `-enableThreadSanitizer YES` flag to `xcodebuild test` command

@see https://developer.apple.com/videos/play/wwdc2017/407/ for more info on Address/Thread/Undefined behavior sanitizers.

**Comment by kenji21** [comment]
@kattrali @supermarin any chance to have some feedback on this PR, important to my eyes get got this merged: our CI marks some builds "stable" because these failing tests are not reported in junit xml file

**Comment by kenji21** [comment]
Just had a bug on a project which was detected by a test, but not reported by our CI (jenkins) due to this issue

Now using our fork within our CI awaiting the PR https://github.com/supermarin/xcpretty/pull/293 to be merged

**Comment by westerlund** [comment]
great work, @kenji21!

it would be great if any of the developers can eye through this, I'm getting these errors as well.

**Comment by supermarin** [comment]
It's merged, given the small performance hit

**Comment by supermarin** [comment]
You can use xcpretty :head if you want to have the newest features without waiting for an official release.

**Comment by kenji21** [comment]
Cool, thanks again for this nice tool helping use diagnose our CI build failure more easily 👍

**Comment by kenji21** [comment]
hmm... did understand what you mean by ":head", I'm using xcpretty installed via `gem install xpretty`, maybe this bugfix can lead to a 0.2.9 version ?

I'm using it with this shell script (not committed to the repo, and PATH correctly setted to point to the repo):

```
..../xcpretty.git [fix-291-tests-restarting-when-fatal-error]
cat xcpretty
#!/bin/sh
BASEDIR=$(dirname $0)

set -x
ruby -rubygems -I $BASEDIR/lib $BASEDIR/bin/xcpretty "$@"
```

**Comment by stidch** [comment]
I see this issue was closed quite a while ago.

I hope someone can tell me what I'm doing wrong, but I'm still miss crashed tests in the XML.

In the log file I see tests failing with
```
Restarting after unexpected exit, crash, or test timeout in TestDummy/test_Dummy(); summary will include totals from previous launches.    
```

When I'm looking for `test_Dummy` in the XML I can't find it. It's missing.

I'm using `Xcpretty 0.3.0` and wonder if there is still an issue or I'm not using the tool correctly.

Any input is appreciated.

Thanks guys!
