### ISSUE TITLE
Screenshots not getting linked with correct method

### ISSUE THREAD

**Issue by aditjain** [supermarin/xcpretty#309]
<img width="750" alt="screen shot 2018-01-17 at 1 52 29 pm" src="https://user-images.githubusercontent.com/4325607/35069015-bdc84d82-fb8d-11e7-9ed2-71525e765003.png">

In a scenario when multiple methods exists with same name, screenshot get attached to any of those methods not to the one it belongs to. If we can attach screenshot with unique combination of <className_methodName> than this can be resolved

see screenshot attached, there are two different methods belonging to two different classes and the screenshot belonged to failed test but it got attached to the passed one.

**Comment by aditjain** [comment]
@mattcotton @supermarin any update

**Comment by mattcotton** [comment]
@aditjain, the naming convention that you suggest is already supported.

Outside of this, I’m not sure that there is much more that we can do, as we only have the name of the test available as something we can link image names to.

**Comment by aditjain** [comment]
@mattcotton what I am saying is can we take a combination of class and method name, that will always be unique? If it is implemented with className_methodName than this bug can be fixed. 

This is impacting HTML reports generated by xcpretty since it is giving false information by attaching failure screenshot with wrong method :(

**Comment by mattcotton** [comment]
@aditjain, I understand what your issue is - support for screenshots with a file name of <classname_testname> was added as part of #280. Have you tried it?

**Comment by aditjain** [comment]
I have screenshot saved like this testApiProfilingSavedSearch_xyz_ui_tests.ApiProfilingSavedSearchTest.png
where testApiProfilingSavedSearch is method name and 
xyz_ui_tests.ApiProfilingSavedSearchTest is class name. 

And I am facing this issue. So it may be because of multiple "_" in the image file? 
I will try a few things at my end and will reach out again.

**Comment by mattcotton** [comment]
@aditjain You have your screenshot names the wrong way around - it needs to be <className_testName>

So in your example, it would be:
xyz_ui_tests.ApiProfilingSavedSearchTest_testApiProfilingSavedSearch.

If “xyz_ui_tests“ is the name of your test target rather than part of the class name, this needs to be removed.

Let me know if you’re still having issues.

**Comment by mattcotton** [comment]
@aditjain are you still having issues with this, or did my comment above resolve your problem?

**Comment by aditjain** [comment]
this can be closed. Thanks much. @mattcotton
