### ISSUE TITLE
when xcode use ccache, the compile_commands.json generated by xcpretty is empty

### ISSUE THREAD

**Issue by HappyMary** [supermarin/xcpretty#310]
when xcode use ccache(https://ccache.samba.org/) to speed up recompilation, the xcodebuild.log generated by xcodebuild contains the compile command string `/Users/nobody/WorkSpace/Demo/Pods/../ccache/ccache-clang * -c /Users/nobody/WorkSpace/Demo/Pods/Target\ Support\ Files/AutoCoding/AutoCoding-dummy.m -o /Users/nobody/Library/Developer/Xcode/DerivedData/Demo-dnvfjufgggbnklfuzqrqhahyymyt/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AutoCoding.build/Objects-normal/x86_64/AutoCoding-dummy.o
`
But the regex match is `    COMPILE_COMMAND_MATCHER = /^\s*(.*\/bin\/clang\s.*\s\-c\s(.*\.(?:m|mm|c|cc|cpp|cxx))\s.*\.o)$/` in parser.rb. So the compile command string not match the matcher in xcpretty.

But oclint-xcodebuild is not match '/bin/clang', the  the compile command string can match the matcher in  oclint-xcodebuild.
@gangadharbonda
@KrauseFx

**Comment by HappyMary** [comment]
@supermarin

**Comment by gangadharbonda** [comment]
@supermarin @kattrali 
Any chance for fixing this issue

**Comment by steipete** [comment]
Can confirm. Tried testing oclint and after numerous compiles, clean and googling I found out that it's ccache.
