### ISSUE TITLE
How to integrate with Jenkins?

### ISSUE THREAD

**Issue by jgale** [supermarin/xcpretty#9]
Our iOS build is done with Jenkins using the Xcode Plugin:
https://wiki.jenkins-ci.org/display/JENKINS/Xcode+Plugin

I was trying to integrate XCPretty into this since it looks very useful. 

I tried adding to the "Custom xcodebuild arguments", e.g.: 

BUILD_NUMBER=${BUILD_NUMBER} ONLY_ACTIVE_ARCH=NO | xcpretty

However I get an error in Jenkins:

```
[workspace] $ /usr/bin/xcodebuild -scheme makeshift -workspace iOS/makeshift.xcworkspace -configuration Dev clean build CONFIGURATION_BUILD_DIR=/Users/Shared/Jenkins/Home/jobs/makeShift-iOS-Dev-TestFlight/workspace/iOS/build BUILD_NUMBER=240 ONLY_ACTIVE_ARCH=NO | xcpretty
Build settings from command line:
    BUILD_NUMBER = 240
    CONFIGURATION_BUILD_DIR = /Users/Shared/Jenkins/Home/jobs/makeShift-iOS-Dev-TestFlight/workspace/iOS/build
    ONLY_ACTIVE_ARCH = NO

xcodebuild: error: Unknown build action '|'.
Build step 'Xcode' marked build as failure
```

It seems to be choking on the pipe. :confused: 

I know this isn't an XCPretty bug, per se, but have you guys investigated how to make this work with Jenkins? Would it be possible to update the documentation if so?

Thanks!
Jeremy

**Comment by gsaslis** [comment]
fwiw, i would also 👍  a jenkins xcode plugin integration. 
great tool btw!

**Comment by yanzhiwei147** [comment]
I meet the problem also.How can i do for integrate into jenkins with Xcode Plugin?
